import os
import base64
from langchain_groq import ChatGroq
from langchain_core.output_parsers.string import StrOutputParser

def format_data_for_ai(diffs, readme_content, commit_messages):
    prompt = None
    # Combine the changes into a string with clear delineation.
    changes = '\n'.join([
        f'File: {file["filename"]}\\Diff: {file["patch"]}\n' 
        for file in diffs
    ])
    # Combine all commit messages
    commit_messages = '\n'.join(commit_messages) + '\n\n'

    # Decode the README content
    readme_content = base64.b64decode(readme_content.content).decode('utf-8')

    # Construct the prompt with clear instructions for the LLM.
    prompt = (
        "Please review the following code changes and commit messages from a GitHub pull request:\n"
        "Code changes from Pull Request:\n"
        f"{changes}\n"
        "Commit messages:\n"
        f"{commit_messages}"
        "Here is the current README file content:\n"
        f"{readme_content}\n"
        "Consider the code changes and commit messages, determine if the README needs to be updated. If so, edit the README, ensuring to maintain its existing style and clarity.\n"
        "Updated README:\n"
    )

    return prompt

def call_ai(prompt):
    client = ChatGroq(api_key=os.getenv('GROQ_API_KEY'), model="llama3-8b-8192")

    try:
        messages = [
            {"role": "system", "content": "You are an AI trained to help with updating README files based on commit messages and code file changes"},
            {"role": "user", "content": prompt}
        ]

        response = client.invoke(input=messages)
        parser = StrOutputParser()
        content = parser.invoke(input=response)

        return content
    except Exception as e:
        print(f"Error making LLM call: {e}")

def update_readme_and_create_pr(repo, updated_readme, readme_sha):
    commit_message = "AI: Proposed README update based on recent code changes."

    commit_sha = os.getenv('COMMIT_SHA')
    main_branch = repo.get_branch('main')
    new_branch_name = f'update-readme-{commit_sha[:7]}'
    new_branch = repo.create_git_ref(ref=f'refs/heads/{new_branch_name}', sha=main_branch.commit.sha)

    repo.update_file("README.md", commit_message, updated_readme, readme_sha, branch=new_branch_name)

    pr_title = "AI: Proposed README update"
    pr_body = "This pull request was automatically generated by AI."
    pr = repo.create_pull(title=pr_title, body=pr_body, head=new_branch_name, base='main')

    return pr